language: java
sudo: false
dist: xenial
branches:
  only:
   - master
before_script:
 - openssl aes-256-cbc -K $encrypted_2ac299456ee4_key -iv $encrypted_2ac299456ee4_iv -in rit.key.enc -out ~/.ssh/rit.key -d
 - cat known_hosts >> ~/.ssh/known_hosts
script: ./gradlew test